name: WeeklyPurchase
version: ${project.version}
main: xyz.masa3mc.weeklypurchase.WeeklyPurchase
api-version: 1.18

commands:
  weeklypurchase:
    usage: /weeklypurchase
    permission: weeklypurchase
